services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/home/backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:
